### ISSUE TITLE
XPath on Multinode Treepicker doesn't seem to work.

### ISSUE THREAD

**Issue by kasperskov909** [umco/umbraco-fluidity#20] opened 2018-02-15 14:17 UTC
I've created a new data type using the multinode treepicker with a specific xpath in Umbraco 7.8 (cloud). The xpath mechanism works fine when used as a property on a document type but not as an editor/data type on a Fluidity field.

Xpath used in my case: `$root//docTypeAlias1//docTypeAlias2`

Note that the "Allow items of type" property on the Multinode Treepicker works fine in Fluidity.

**Comment by mattbrailsford** [comment] 2018-03-07 08:43
Ok, so I've found the root of the cause, but not sure of the fix at the moment. It looks like MNTP calls `entityResource.getByQuery` which accepts the xpath but also requires a node id for context, which it is currently getting from the `$routeParms.id` property, which in a Fluidity context is something like `collectionAlias!entityId`. That's fine for us, but it looks like the `getByQuery` api expects that value to be an integer and so is throwing an error.

The only workaround I can think of atm would be to intercept calls to `getByQuery` and if id looks like a fluidity based id, then set it to -1, but I'm not sure how happy I am with doing that at the moment.

**Comment by mattbrailsford** [comment] 2018-03-07 09:10
Ok, in looking through the source, it seems I'm already doing some overriding in places so what does one more hurt :)

This issue is fixed in commit bb4c6c0. I've also added some notes to the known issues documentation as the only xpath statements that will be supported are those starting `$root`. All others require a content node context, which, not being in the content section means we can't provide.

**Closed by mattbrailsford** 2018-03-07 09:10 UTC
